### PR TITLE
Fix #737 validate advisory version, log errors in parsing versions

### LINKED ISSUE #737: Validate advisory payloads, skip invalid ones, and log their output
Advisories in the Github advisory DB are getting worse and worse in quality, mostly because many sources start reporting them.

It is a good idea to start validating version ranges, and rejecting anything that isn't 100% clear.

Whilst that lowers security, it is better than not having an updated advisory compendium due to a crash while reading an advisory.

Composer validation must still pass, once `composer.json` is fully generated.

### PR DESCRIPTION
**Pull request by Ocramius**
Fixes #737

### CODE REVIEW

File: src/Roave/SecurityAdvisories/Advisory.php [hunk 1]
```diff
@@ -75,6 +75,7 @@ public function getVersionConstraints(): array
     /** @psalm-suppress ImpureFunctionCall - conditional purity {@see https://github.com/azjezz/psl/issues/130} */
     public function getConstraint(): string|null
     {
+        // @TODO possibly worth merging the constraints here
         // @TODO may want to escape this
```
Comment (Ocramius) [inline src/Roave/SecurityAdvisories/Advisory.php]: To be adjusted

File: src/Roave/SecurityAdvisories/AdvisorySources/GetAdvisoriesFromGithubApi.php [hunk 2]
```diff
@@ -88,9 +89,11 @@ public function __invoke(): Generator
                         'branches'  => [['versions' => $versions]],
                     ],
                 );
-            } catch (InvalidPackageName) {
+            } catch (InvalidPackageName | UnexpectedValueException) {
                 // Sometimes, github advisories publish CVEs with malformed package names, and that
                 // should not crash our entire pipeline.
+                // Also, the advisories in the github database have terrible version quality: skipping
+                // all advisories for which we couldn't parse a version.
                 // @TODO add logging here?
```
Comment (Ocramius) [inline src/Roave/SecurityAdvisories/AdvisorySources/GetAdvisoriesFromGithubApi.php]: To be implemented here, before merging

File: test/RoaveTest/SecurityAdvisories/ComponentTest.php [hunk 3]
```diff
@@ -229,20 +229,21 @@ public function testSortComplexAdvisoriesWithRealCase(
...
+//                        'versions' => ['>=2.1.0', '<2.1.2'],
+//                    ],
+//                ],
+//                [
+//                    '2.1.x' => [
+//                        'versions' => ['>=2.1.0-beta1', '<2.1.3'],
+//                    ],
+//                ],
+//                '>=2.1.0.0-beta1,<2.1.3',
+//            ],
```
Comment (Ocramius) [inline test/RoaveTest/SecurityAdvisories/ComponentTest.php]: to be re-enabled

File: src/Roave/SecurityAdvisories/Component.php [hunk 4]
```diff
@@ -60,6 +60,7 @@ public function getConflictConstraint(): string
      */
     private function deDuplicateConstraints(array $constraints): array
     {
+        // @TODO to be replaced by a single array_reduce
```
Comment (Ocramius) [inline src/Roave/SecurityAdvisories/Component.php]: Can be massively simplified

File: test/RoaveTest/SecurityAdvisories/VersionConstraintTest.php [hunk 5]
```diff
@@ -551,26 +290,27 @@ public function strictlyOverlappingRangesProvider(): array
...
+            ['>1-alpha.1,<2-alpha.1', '>=2-alpha.1', '>1.0.0.0-alpha1'],
+            ['>1-alpha.1,<2-alpha.1', '<=1-alpha.1', '<2.0.0.0-alpha1'],
+            ['>=1-alpha.1,<2-alpha.1', '<1-alpha.1', '<2.0.0.0-alpha1'],
             // test overlapping of flags
-            ['>1-a,<1-rc', '>1-b,<1-stable', '>1-a,<1-stable'],
-            ['>1-b,<1-stable', '>1-rc,<1', '>1-b,<1'],
-            ['>1-rc,<1', '>1-stable,<1-patch', '>1-rc,<1-patch'],
-            ['>1-a,<1-rc', '>1-beta,<1-rc', '>1-a,<1-rc'],
+            //['>1-a,<1-rc', '>1-b,<1-stable', '>1-a,<1-stable'],
+            ['>1-a,<1-rc', '>1-b,<1-stable', '>1.0.0.0-alpha,<1.0.0.0-RC-dev'], // @TODO potential bug
```
Comment (Ocramius) [inline test/RoaveTest/SecurityAdvisories/VersionConstraintTest.php]: Check this TODO
